#!/usr/bin/env python3
"""
AWS Service Cost Breakdown Generator
Parses AWS Cost Explorer inventory JSON reports (generated by get_cost_inventory.py)
and produces comprehensive, tabular markdown reports detailing per-service spend,
monthly trends, regional distribution, usage types, and purchase options.

Output Location:
    output/cost-breakdown/<aws_account_id>/service-cost-breakdown-<account_id>-<timestamp>.md

Usage:
    # 1. Automatic scan of ALL accounts in output/ (no args required):
    python tools/generate_service_cost_breakdown.py

    # 2. Specific account by ID:
    python tools/generate_service_cost_breakdown.py -a 123456789012
    python tools/generate_service_cost_breakdown.py -id 123456789012

    # 3. By AWS profile name:
    python tools/generate_service_cost_breakdown.py -p 123456789012_AdministratorAccess

    # 4. By specific directory containing cost JSON files:
    python tools/generate_service_cost_breakdown.py --path output/123456789012/cost/

    # 5. By exact JSON file:
    python tools/generate_service_cost_breakdown.py -i output/123456789012/cost/cost-inventory-123456789012-20260902-083007.json

    # 6. Custom output file or directory:
    python tools/generate_service_cost_breakdown.py -a 123456789012 -o output/cost-breakdown/123456789012/custom-report.md
"""

import argparse
import glob
import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = ROOT_DIR / "output"
DEFAULT_BREAKDOWN_DIR = ROOT_DIR / "output" / "cost-breakdown"

# Ensure common is importable
sys.path.insert(0, str(ROOT_DIR))


def format_currency(val, decimals=2):
    """Format float into USD currency string."""
    if val is None:
        return "$0.00"
    if abs(val) < 0.005 and val != 0:
        return f"${val:.4f}"
    return f"${val:,.{decimals}f}"


def format_pct(val):
    """Format percentage float."""
    if val is None or val == 0:
        return "0.0%"
    if val < 0.05:
        return "<0.1%"
    return f"{val:.1f}%"


def slugify(text):
    """Create GitHub markdown anchor slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    return slug


def resolve_account_from_profile(profile_name):
    """Attempt to resolve account ID from profile name or conf/accounts.yaml."""
    # Check if 12-digit number is in profile name
    match = re.search(r"(\d{12})", profile_name)
    if match:
        return match.group(1)

    try:
        from common import get_accounts
        accounts = get_accounts()
        for acct in accounts:
            if acct.get("profile") == profile_name:
                return str(acct.get("account_id", ""))
    except Exception:
        pass
    return profile_name


def find_cost_files_in_dir(directory):
    """Find all cost-inventory-*.json or cost JSONs in a directory."""
    dir_path = Path(directory)
    if not dir_path.exists():
        return []

    # Try cost-inventory pattern first
    files = sorted(glob.glob(str(dir_path / "cost-inventory-*.json")))
    if not files:
        files = sorted(glob.glob(str(dir_path / "**" / "cost-inventory-*.json"), recursive=True))
    if not files:
        files = sorted(glob.glob(str(dir_path / "*.json")))
    return files


def find_latest_cost_file_for_account(account_id, base_dir=None):
    """Find the most recent cost-inventory JSON for an account."""
    if base_dir is None:
        base_dir = DEFAULT_OUTPUT_DIR
    pattern = os.path.join(base_dir, str(account_id), "cost", "cost-inventory-*.json")
    files = sorted(glob.glob(pattern))
    if not files:
        return None
    return files[-1]


def discover_all_account_cost_files(base_dir=None):
    """Discover the latest cost inventory file for every account in output/."""
    if base_dir is None:
        base_dir = DEFAULT_OUTPUT_DIR

    account_files = {}
    if not os.path.exists(base_dir):
        return account_files

    for entry in sorted(os.listdir(base_dir)):
        entry_path = os.path.join(base_dir, entry)
        if not os.path.isdir(entry_path):
            continue
        # Skip special/non-account directories
        if entry.startswith(("_", ".")) or entry in ("audit", "okf", "cost-breakdown"):
            continue

        cost_dir = os.path.join(entry_path, "cost")
        if os.path.exists(cost_dir):
            files = sorted(glob.glob(os.path.join(cost_dir, "cost-inventory-*.json")))
            if files:
                account_files[entry] = files[-1]

    return account_files


def parse_cost_inventory(data, min_spend=0.0):
    """Parse raw cost JSON into structured per-service analytics."""
    account_id = str(data.get("name") or data.get("account_id") or "Unknown")
    profile = data.get("profile_used", "")
    period = data.get("period", {})
    ytd_total = float(data.get("ytd_total", 0.0))
    prior_month_total = float(data.get("prior_month_total", 0.0))
    mtd_total = float(data.get("mtd_total", 0.0))

    # Monthly periods in order
    monthly_items = data.get("ytd_by_service_monthly", [])
    distinct_months = sorted(list(set(item["period_start"] for item in monthly_items)))

    # Per-service monthly buckets: service -> month -> unblended_cost
    service_monthly = defaultdict(lambda: defaultdict(float))
    service_ytd_totals = defaultdict(float)

    for item in monthly_items:
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        month = item["period_start"]
        cost = float(item.get("unblended_cost", 0.0))
        service_monthly[service_name][month] += cost
        service_ytd_totals[service_name] += cost

    # Fallback if ytd_by_service_monthly is empty but mtd/prior_month exists
    if not service_ytd_totals:
        for item in data.get("mtd_by_service", []):
            s_name = item["keys"][0] if item.get("keys") else "Unknown"
            service_ytd_totals[s_name] += float(item.get("unblended_cost", 0.0))

    # Prior month by service
    service_prior_month = defaultdict(float)
    for item in data.get("prior_month_by_service", []):
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        service_prior_month[service_name] += float(item.get("unblended_cost", 0.0))

    # MTD by service
    service_mtd = defaultdict(float)
    for item in data.get("mtd_by_service", []):
        service_name = item["keys"][0] if item.get("keys") else "Unknown"
        service_mtd[service_name] += float(item.get("unblended_cost", 0.0))

    # Regional breakdown: service -> region -> cost
    service_regions = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_region", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            region = item["keys"][1]
            service_regions[s_name][region] += float(item.get("unblended_cost", 0.0))

    # Usage type breakdown: service -> usage_type -> cost
    service_usage_types = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_usage_type", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            ut = item["keys"][1]
            service_usage_types[s_name][ut] += float(item.get("unblended_cost", 0.0))

    # Purchase option breakdown: service -> option -> cost
    service_purchase_options = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_purchase_option", []):
        if len(item.get("keys", [])) >= 2:
            s_name = item["keys"][0]
            opt = item["keys"][1]
            service_purchase_options[s_name][opt] += float(item.get("unblended_cost", 0.0))

    # Linked account breakdown: service -> linked_account -> cost
    service_linked_accounts = defaultdict(lambda: defaultdict(float))
    for item in data.get("by_linked_account", []):
        if len(item.get("keys", [])) >= 2:
            acct = item["keys"][0]
            s_name = item["keys"][1]
            service_linked_accounts[s_name][acct] += float(item.get("unblended_cost", 0.0))

    # All unique services sorted by YTD spend descending
    all_service_names = set(service_ytd_totals.keys()) | set(service_prior_month.keys()) | set(service_mtd.keys())
    sorted_services = sorted(
        [s for s in all_service_names if service_ytd_totals[s] >= min_spend or service_prior_month[s] > 0 or service_mtd[s] > 0],
        key=lambda s: service_ytd_totals[s],
        reverse=True,
    )

    return {
        "account_id": account_id,
        "profile": profile,
        "period": period,
        "ytd_total": ytd_total,
        "prior_month_total": prior_month_total,
        "mtd_total": mtd_total,
        "distinct_months": distinct_months,
        "sorted_services": sorted_services,
        "service_ytd_totals": service_ytd_totals,
        "service_monthly": service_monthly,
        "service_prior_month": service_prior_month,
        "service_mtd": service_mtd,
        "service_regions": service_regions,
        "service_usage_types": service_usage_types,
        "service_purchase_options": service_purchase_options,
        "service_linked_accounts": service_linked_accounts,
    }


def month_header(date_str):
    """Convert '2026-01-01' into 'Jan 2026'."""
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        return dt.strftime("%b %Y")
    except Exception:
        return date_str


def generate_markdown_report(parsed, top_n=10):
    """Generate presentation-ready tabular markdown document."""
    account_id = parsed["account_id"]
    period = parsed["period"]
    ytd_total = parsed["ytd_total"]
    prior_month_total = parsed["prior_month_total"]
    mtd_total = parsed["mtd_total"]
    months = parsed["distinct_months"]
    services = parsed["sorted_services"]

    lines = []
    lines.append(f"# AWS Service Cost Breakdown Report — Account `{account_id}`\n")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ")
    lines.append(f"**Account ID:** `{account_id}` | **Profile:** `{parsed['profile'] or 'N/A'}`  ")
    lines.append(
        f"**Analysis Period:** YTD `{period.get('ytd_start', '2026-01-01')}` to `{period.get('end', 'Present')}` "
        f"(Prior Month: `{period.get('prior_month_start', '')}` to `{period.get('prior_month_end', '')}`)\n"
    )
    lines.append("---\n")

    # High-level summary scorecard
    lines.append("## 📊 Executive Spend Summary\n")
    lines.append("```")
    lines.append("┌──────────────────────────────────────────────────────────────────────────────────────────────────┐")
    lines.append("│                                  ACCOUNT COST SUMMARY SCORECARD                                  │")
    lines.append("├──────────────────────────────┬──────────────────────────────┬────────────────────────────────────┤")
    lines.append("│       Total YTD Spend        │      Prior Month Spend       │          Current MTD Spend         │")
    lines.append(f"│       {format_currency(ytd_total):<22} │       {format_currency(prior_month_total):<22} │          {format_currency(mtd_total):<26}│")
    lines.append(f"│   (Services Tracked: {len(services):<6}) │   (Prior Month Total Spend)  │          (Month-to-Date Spend)     │")
    lines.append("└──────────────────────────────┴──────────────────────────────┴────────────────────────────────────┘")
    lines.append("```\n")

    # Master Ranking Table
    lines.append("### 🏆 Master Service Spend Ranking (All Services)\n")
    lines.append("| Rank | Service Name | YTD Spend | % of Total | Prior Month Spend | MTD Spend | MoM Trend |")
    lines.append("|---|---|---:|---:|---:|---:|---:|")

    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        pct_of_total = (ytd_spend / ytd_total * 100) if ytd_total > 0 else 0.0
        pm_spend = parsed["service_prior_month"].get(s_name, 0.0)
        mtd_spend = parsed["service_mtd"].get(s_name, 0.0)

        # Calculate MoM change
        if len(months) >= 2:
            prev_m = parsed["service_monthly"][s_name].get(months[-2], 0.0)
            prior_prev_m = parsed["service_monthly"][s_name].get(months[-3], 0.0) if len(months) >= 3 else 0.0
            if prior_prev_m > 0:
                diff = prev_m - prior_prev_m
                diff_pct = (diff / prior_prev_m) * 100
                trend_str = f"{'+' if diff >= 0 else ''}{diff_pct:.1f}%"
            else:
                trend_str = "—"
        else:
            trend_str = "—"

        anchor = slugify(f"{rank}. {s_name}")
        lines.append(
            f"| **{rank}** | [{s_name}](#{anchor}) | **{format_currency(ytd_spend)}** | {format_pct(pct_of_total)} | {format_currency(pm_spend)} | {format_currency(mtd_spend)} | {trend_str} |"
        )

    lines.append("\n---\n")

    # Table of Contents
    lines.append("## 📑 Table of Contents\n")
    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        anchor = slugify(f"{rank}. {s_name}")
        lines.append(f"- [{rank}. {s_name} ({format_currency(ytd_spend)})](#{anchor})")

    lines.append("\n---\n")

    # Per-Service Detail Sections
    lines.append("## 🔍 Detailed Per-Service Tabular Cost Breakdown\n")

    for rank, s_name in enumerate(services, start=1):
        ytd_spend = parsed["service_ytd_totals"].get(s_name, 0.0)
        pm_spend = parsed["service_prior_month"].get(s_name, 0.0)
        mtd_spend = parsed["service_mtd"].get(s_name, 0.0)
        pct_of_total = (ytd_spend / ytd_total * 100) if ytd_total > 0 else 0.0
        avg_monthly = ytd_spend / max(1, len(months)) if months else ytd_spend

        lines.append(f"### {rank}. {s_name}\n")
        lines.append(f"- **Total YTD Spend:** `{format_currency(ytd_spend)}` ({format_pct(pct_of_total)} of account spend)")
        lines.append(f"- **Prior Month Spend:** `{format_currency(pm_spend)}` | **Current MTD Spend:** `{format_currency(mtd_spend)}`")
        lines.append(f"- **Average Monthly Spend:** `{format_currency(avg_monthly)}/mo`\n")

        # 1. Monthly Trend Table (if months exist)
        if months:
            lines.append("#### 📅 Monthly Spend History")
            month_headers = [month_header(m) for m in months]
            lines.append("| " + " | ".join(month_headers) + " | **Total YTD** | **Monthly Avg** |")
            lines.append("|" + "|".join(["---:"] * (len(months) + 2)) + "|")

            row_vals = [format_currency(parsed["service_monthly"][s_name].get(m, 0.0)) for m in months]
            row_vals.append(f"**{format_currency(ytd_spend)}**")
            row_vals.append(f"**{format_currency(avg_monthly)}**")
            lines.append("| " + " | ".join(row_vals) + " |\n")

        # 2. Regional Breakdown
        regions = parsed["service_regions"].get(s_name, {})
        if regions:
            sorted_regions = sorted(regions.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### 🌐 Top Regions (Top {min(len(sorted_regions), top_n)})")
            lines.append("| Region | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for reg, r_cost in sorted_regions:
                r_pct = (r_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{reg}` | {format_currency(r_cost)} | {format_pct(r_pct)} |")
            lines.append("")

        # 3. Usage Type Breakdown
        usage_types = parsed["service_usage_types"].get(s_name, {})
        if usage_types:
            sorted_usage = sorted(usage_types.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### ⚙️ Top Usage Types (Top {min(len(sorted_usage), top_n)})")
            lines.append("| Usage Type | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for ut, u_cost in sorted_usage:
                u_pct = (u_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{ut}` | {format_currency(u_cost)} | {format_pct(u_pct)} |")
            lines.append("")

        # 4. Purchase Option Breakdown (if >1 option or meaningful)
        p_options = parsed["service_purchase_options"].get(s_name, {})
        if len(p_options) > 1 or (len(p_options) == 1 and list(p_options.keys())[0] != "On Demand Instances"):
            sorted_opts = sorted(p_options.items(), key=lambda x: x[1], reverse=True)
            lines.append("#### 🏷️ Purchase Options Breakdown")
            lines.append("| Purchase Option | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for opt, o_cost in sorted_opts:
                o_pct = (o_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| {opt} | {format_currency(o_cost)} | {format_pct(o_pct)} |")
            lines.append("")

        # 5. Linked Account Breakdown (if multiple accounts present)
        linked_accts = parsed["service_linked_accounts"].get(s_name, {})
        if len(linked_accts) > 1:
            sorted_accts = sorted(linked_accts.items(), key=lambda x: x[1], reverse=True)[:top_n]
            lines.append(f"#### 🏢 Top Linked Accounts (Top {min(len(sorted_accts), top_n)})")
            lines.append("| Linked Account ID | YTD Spend | % of Service Spend |")
            lines.append("|---|---:|---:|")
            for acct, a_cost in sorted_accts:
                a_pct = (a_cost / ytd_spend * 100) if ytd_spend > 0 else 0.0
                lines.append(f"| `{acct}` | {format_currency(a_cost)} | {format_pct(a_pct)} |")
            lines.append("")

        lines.append("---\n")

    return "\n".join(lines)


def process_single_cost_file(json_file_path, output_override=None, min_spend=0.0, top_n=10):
    """Process a single JSON file and write its markdown breakdown report."""
    if not os.path.exists(json_file_path):
        print(f"⚠️ File not found: {json_file_path}", file=sys.stderr)
        return None

    print(f"📖 Processing: {json_file_path}")
    with open(json_file_path, "r") as f:
        data = json.load(f)

    parsed = parse_cost_inventory(data, min_spend=min_spend)
    account_id = parsed["account_id"]
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    # Determine output destination
    if output_override:
        out_p = Path(output_override)
        if out_p.is_dir() or output_override.endswith(os.sep):
            os.makedirs(out_p, exist_ok=True)
            output_file = str(out_p / f"service-cost-breakdown-{account_id}-{timestamp}.md")
        else:
            output_file = str(out_p)
    else:
        # Standard folder: output/cost-breakdown/<account_id>/
        account_out_dir = DEFAULT_BREAKDOWN_DIR / account_id
        os.makedirs(account_out_dir, exist_ok=True)
        output_file = str(account_out_dir / f"service-cost-breakdown-{account_id}-{timestamp}.md")

    os.makedirs(os.path.dirname(os.path.abspath(output_file)), exist_ok=True)
    report_md = generate_markdown_report(parsed, top_n=top_n)

    with open(output_file, "w") as f:
        f.write(report_md)

    print(f"  ✅ Saved: {output_file} ({len(parsed['sorted_services'])} services, YTD: {format_currency(parsed['ytd_total'])})")
    return output_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate per-service tabular markdown cost breakdown from AWS Cost Explorer inventory"
    )
    parser.add_argument("-i", "--input", "--file", default=None, help="Path to a specific cost inventory JSON file")
    parser.add_argument("-a", "--account", "-id", "--id", default=None, help="AWS Account ID")
    parser.add_argument("-p", "--profile", default=None, help="AWS profile name")
    parser.add_argument("--path", "-d", default=None, help="Directory path containing cost JSON file(s)")
    parser.add_argument("-o", "--output", default=None, help="Output markdown file or directory path")
    parser.add_argument("--min-spend", type=float, default=0.0, help="Minimum YTD spend in USD to include (default: 0.0)")
    parser.add_argument("--top-n", type=int, default=10, help="Max items in region/usage tables (default: 10)")
    args = parser.parse_args()

    # Case 1: Specific JSON file provided via -i/--file
    if args.input:
        process_single_cost_file(args.input, output_override=args.output, min_spend=args.min_spend, top_n=args.top_n)
        return

    # Case 2: Specific directory provided via --path/-d
    if args.path:
        files = find_cost_files_in_dir(args.path)
        if not files:
            print(f"❌ Error: No cost JSON files found in {args.path}", file=sys.stderr)
            sys.exit(1)
        print(f"🔍 Found {len(files)} cost file(s) in {args.path}")
        for f in files:
            process_single_cost_file(f, output_override=args.output, min_spend=args.min_spend, top_n=args.top_n)
        return

    # Case 3: Specific account ID or profile provided
    target_account = args.account
    if not target_account and args.profile:
        target_account = resolve_account_from_profile(args.profile)

    if target_account:
        cost_file = find_latest_cost_file_for_account(target_account)
        if not cost_file:
            print(f"❌ Error: No cost inventory JSON found for account {target_account} in output/{target_account}/cost/", file=sys.stderr)
            sys.exit(1)
        process_single_cost_file(cost_file, output_override=args.output, min_spend=args.min_spend, top_n=args.top_n)
        return

    # Case 4: No arguments given — search ALL account folders in output/
    print("🔍 No arguments specified. Scanning all account directories in output/...")
    account_files = discover_all_account_cost_files()

    if not account_files:
        print("⚠️ No cost inventory files found in output/<account>/cost/", file=sys.stderr)
        sys.exit(1)

    print(f"📊 Discovered cost inventory for {len(account_files)} account(s):\n")
    generated_reports = []
    for acct, c_file in account_files.items():
        out = process_single_cost_file(c_file, output_override=args.output, min_spend=args.min_spend, top_n=args.top_n)
        if out:
            generated_reports.append(out)

    print(f"\n🎉 Done! Successfully generated {len(generated_reports)} cost breakdown reports in {DEFAULT_BREAKDOWN_DIR}/")


if __name__ == "__main__":
    main()
